version: '3.7'
services:
  postgres:
    image: postgres:12.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=app
    ports:
      - '5432:5432'
  node-app:
    build: ./artifacts/gate-simulator
    image: latest
    container_name: node
    ports:
      - '9999:9999'

