version: '3.7'
services:
  node-app:
    build: ./artifacts/gate-simulator
    image: latest
    container_name: node
    ports:
      - '9999:9999'
  postgresql:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=margo
      - POSTGRES_PASSWORD=queenMargo