version: '3.7'
services:
  postgresql:
    image: postgres:latest
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=margo
      - POSTGRES_PASSWORD=queenMargo